{
 "title": "Pool Sensor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pool_temp\nFROM pool_webhooks\nORDER BY time_stamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (100 / 1.8) * (battery_voltage - 1.88) AS battery_voltage\nFROM pool_webhooks\nORDER BY time_stamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Temperature History",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT pool_temp, time_stamp FROM pool_webhooks ORDER BY time_stamp DESC LIMIT 1440 "
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT (100 / 1.8) * (battery_voltage - 1.88) AS battery_voltage, time_stamp\nFROM pool_webhooks\nORDER BY time_stamp DESC\nLIMIT 1440;"
    }
   ]
  },
  {
   "title": "Connection Strength (rssi)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT rssi, time_stamp\nFROM pool_webhooks\nORDER BY time_stamp DESC\nLIMIT 1440;"
    }
   ]
  }
 ]
}